{% set name = "crashtest" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42ca7b6ce88b6c7433e2ce47ea884e91ec93104a4b754998be498a8e6c3d37dd

build:
  number: 1
  noarch: python
  script:
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry-core >=1.0.0a5
  run:
    - python >=3.6,<4.0

test:
  imports:
    - crashtest
    - crashtest.contracts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdispater/crashtest
  summary: Manage Python errors with ease
  description: Crashtest is a Python library that makes exceptions handling and inspection easier.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/sdispater/crashtest
  doc_url: https://github.com/sdispater/crashtest/blob/master/README.md

extra:
  recipe-maintainers:
    - ocefpaf
