{% set name = "crashtest" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crashtest-{{ version }}.tar.gz
  sha256: 80d7b1f316ebfbd429f648076d6275c877ba30ba48979de4191714a75266f0ce

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.1.0
    - wheel
  run:
    - python

test:
  imports:
    - crashtest
    - crashtest.contracts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdispater/crashtest
  summary: Manage Python errors with ease
  description: Crashtest is a Python library that makes exceptions handling and inspection easier.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/sdispater/crashtest
  doc_url: https://github.com/sdispater/crashtest/blob/master/README.md

extra:
  recipe-maintainers:
    - ocefpaf
